---
- name: Configure Papertrail managed configuration file
  template:
    src: papertrail_conf.yml.j2
    dest: "{{ papertrail_config_file_path }}/{{ papertrail_config_file_name }}"
    owner: root
    group: root
    mode: 0644
    force: true
  notify: restart papertrail
  when: papertrail_managed_conf_file | bool

- name: Enable Papertrail service
  service:
    name: "{{ papertrail_service_name }}"
    enabled: true
  when: papertrail_service_enabled | bool

- name: Start Papertrail service
  service:
    name: "{{ papertrail_service_name }}"
    state: started
  when: papertrail_service_started | bool
