---
- name: Set installer arquitecture
  set_fact:
    installer_arch: "amd64"
  when: ansible_architecture == "x86_64"

- name: Include os family variables
  include_vars:
    file: "{{ ansible_os_family }}.yml"

- name: Set papertrail download url
  set_fact:
    papertrail_download_url: "{{ __papertrail_download_url }}"
  when: papertrail_download_url is not defined

- name: Set papertrail config file path
  set_fact:
    papertrail_config_file_path: "{{ __papertrail_config_file_path }}"
  when: papertrail_config_file_path is not defined

- name: Set papertrail config file name
  set_fact:
    papertrail_config_file_name: "{{ __papertrail_config_file_name }}"
  when: papertrail_config_file_name is not defined

- name: Set papertrail package name
  set_fact:
    papertrail_package_name: "{{ __papertrail_package_name }}"
  when: papertrail_package_name is not defined

- name: Set papertrail service name
  set_fact:
    papertrail_service_name: "{{ __papertrail_service_name }}"
  when: papertrail_service_name is not defined
