---
- name: Set installer arquitecture
  set_fact:
    papertrail_installer_arch: "amd64"
  when: ansible_architecture == "x86_64"

- name: Include os family variables
  include_vars:
    file: "{{ ansible_os_family }}.yml"
