---
- name: Converge
  hosts: all
  vars:
    papertrail_version: "0.19"
    papertrail_destination_host: localhost
    papertrail_destination_port: 12345
    papertrail_custom_hostname: "host-01"
    papertrail_destination_protocol: tls
    papertrail_files_to_log:
      - path: /var/log/nginx.log
        tag: nginx
      - path: /var/log/httpd.log
        tag: apache
      - /var/log/yum.log
      - /var/log/audit/*.log
    papertrail_files_to_exclude:
      - /var/log/yum.log
    papertrail_log_facility: local7
    papertrail_log_severity: warn
    papertrail_exclude_patterns:
      - this is a test
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
